site_name: 12-Week Python Specialization
site_url: https://qurioskill.github.io/python-specialization/
theme:
  name: material
  language: en
  logo: assets/logo.jpg
  palette:
    - scheme: default
      primary: amber
      accent: Turquoise Green
  features:
    - navigation.instant       # fast page transitions
    - navigation.sections
    - search.highlight
    - content.code.annotate    # call-out markers in code blocks

extra:
  analytics:
    provider: google
    property: G-PNJBZPP9PG

nav:
  - Overview: index.md
  - Curriculum Snapshot: curriculum-snapshot.md
  - Payment and Value Breakdown: payment-value.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
