site_name: 12-Week Python Specialization
site_url: https://qurioskill.github.io/python-specialization/
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: Deep Navy Blue
      accent: Turquoise Green
  features:
    - navigation.instant       # fast page transitions
    - navigation.sections
    - search.highlight
    - content.code.annotate    # call-out markers in code blocks
nav:
  - What is it?: index.md
  - Register Now!: register.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
